name: terraform-ci
on:
  pull_request:
permissions:
  id-token: write
  actions: read
  checks: read
  contents: read
  pull-requests: write
  security-events: write
jobs:
  ci:
    uses: SPHTech-Platform/reusable-workflows/.github/workflows/terraform.yaml@v4
    with:
      upload_sarif: true
      runner_label: platform-eng-ent-v2-dual
    secrets: inherit
